name: Build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true

      - name: Install CocoaPods
        run: gem install cocoapods

      - name: Pod lib lint
        run: pod lib lint --allow-warnings --verbose

      - name: Swift package validation
        run: swift package resolve
