name: Publish Authsignal iOS Package

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy to CocoaPods
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
        
    - name: Install CocoaPods
      run: gem install cocoapods

    - name: Deploy to CocoaPods
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod lib lint --allow-warnings
        pod trunk push --allow-warnings 